version: '3.4'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: php-dev
      args:
        PHP_EXTENSIONS: pdo_mysql redis igbinary bcmath pdo_pgsql xdebug
    volumes:
      - ./:/var/www/html
    image: attendance-system/php:8.2-apache
    container_name: attendance-system
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - db
    command:
      - bash
      - -c
      - |
        composer install;
        php artisan migrate;
        php artisan serve --host 0.0.0.0
    mem_limit: 2G
    networks:
      - default
  db:
    image: ankane/pgvector:v0.4.4
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        PGDATA: /var/lib/postgresql/data
    volumes:
        - db-data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "5432:5432"
    mem_limit: 600M
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-d", "${DB_DATABASE}"]
      interval: 40s
      timeout: 15s
      retries: 2
      start_period: 10s
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
        PGADMIN_DEFAULT_EMAIL: "${DB_USERNAME}@system.com"
        PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
        PGADMIN_LISTEN_PORT: 80
    ports:
        - "7001:80"
    volumes:
        - pgadmin-data:/var/lib/pgadmin4
        - ./pgadmin4/servers.json:/pgadmin4/servers.json
    links:
        - "db:pgsql-server"
    mem_limit: 400M

volumes:
    db-data:
    pgadmin-data:
